export enum GameActions {
  INCREMENT_ROUND = `INCREMENT_STEP`,
  INCREMENT_MISTAKES = `INCREMENT_MISTAKES`,
  RESET_GAME = `RESET_GAME`,
  TICK_TIMER = `TICK_TIMER`,
  FINISH_GAME = `FINISH_GAME`,
}

export enum UserActions {
  SET_USER = `SET_USER`,
  PUSH_NEW_RESULT = `PUSH_NEW_RESULT`,
  LOG_OUT = `LOG_OUT`,
}
